---
title: "p8105_hw1_bp2678"
author: "Brady Pham"
date: 2023-09-22
output: github_document
## 
---

```{r}
library(tidyverse)
library(rvest)
library(httr)
library(rvest)
```

imort NSDUH
```{r}
nsduh_url = "https://www.samhsa.gov/data/sites/default/files/NSDUHsaeShortTermCHG2015/NSDUHsaeShortTermCHG2015.htm"
```


```{r}
nsduh_html = 
  read_html(nsduh_url)
```

```{r}
marj_use_df =
nsduh_html |>
  html_table() |>
  first() |>
slice(-1)
```

import star wars 
```{r}
swm_url = 
  "https://www.imdb.com/list/ls070150896/"

swm_html =
  read_html(swm_url)
```


```{r}
swm_title_vec = 
  swm_html |>
  html_elements(".lister-item-header a") |>
  html_text()

swm_gross_rev_vec = 
  swm_html |>
  html_elements(".text-muted .ghost~ .text-muted+ span") |>
  html_text()

swm_df = 
  tibble(
    title = swm_title_vec, gross_rev = swm_gross_rev_vec
  )

```

##APIs
get water data from nyc

```{r}
nyc_water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |>
  content("parsed")
```


BRFSS data
```{r}
brfss_df = 
  GET("https://data.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |>
  content("parsed")
```

Try it now
```{r}
poke_df = 
  GET("https://pokeapi.co/api/v2/pokemon/ditto") |>
  content()

```


2ND PART

```{r}
string_vec = c("my", "name", "is", "Brady")

str_detect(string_vec, "Brady")
str_replace(string_vec, "Brady", "brady")
```


```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think")
```




















